### ISSUE TITLE
DiscordのBot通知を埋め込みメッセージに変更

### ISSUE THREAD

**Issue by oshiteku** [zio3/VetCoin#2]
VetCoinからのDMメッセージや新着お仕事通知のメッセージを埋め込みメッセージに変更したいです。
埋め込みメッセージを使えば、情報量が多く見やすい表示になります。加えて、OGPの展開も避けられます。

参考：
- https://birdie0.github.io/discord-webhooks-guide/discord_webhook.html

**Comment by zio3** [comment]
すばらしいですね。知らなかったです。これぜひやりたいですね。

**Comment by zio3** [comment]
他の開発でも利用したいのもあって、こちらで引き取りたいです。

**Comment by zio3** [comment]
対応しました。
